vector: vector.cpp
	rm a.out | g++ vector.cpp && ./a.out
multi_map: multi_map.cpp
	rm a.out | g++ multi_map.cpp && ./a.out
string: string.cpp
	rm a.out | g++ string.cpp && ./a.out
map: map.cpp
	rm a.out | g++ map.cpp && ./a.out