

all: template_syntax.cpp
	g++ template_syntax.cpp
	./a.out

sort: selectSort.cpp
	g++ selectSort.cpp
	./a.out

diff: funcTemplateDiffClassTemplate.cpp
	g++ funcTemplateDiffClassTemplate.cpp
	./a.out

friend: templateFriend.cpp
	g++ templateFriend.cpp
	./a.out
arr: myArray.cpp
	g++ myArray.cpp
	./a.out